[package]
name = "itwas"
version = "0.1.0"
edition = "2024"
description = "A fast interactive search for Jujutsu history"
license = "MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
ratatui = "0.29"
regex = "1.11"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = { level = "warn", priority = -1 }
